export const  flavorlists = [
  {
    name: "RUSH: 999999999",
    color: "brown",
    num:1,
    rotation: "md:rotate-[-3deg] rotate-0",
  },
  {
    name: "Interplanetary Criminal",
    color: "red",
    num:12,
    rotation: "md:rotate-[8deg] rotate-0",
  },
  {
    name: "SABAI",
    color: "blue",
    num:13,
    rotation: "md:rotate-[-8deg] rotate-0",
  },
  {
    name: "Maddix",
    color: "orange",
    num:16,
    rotation: "md:rotate-[8deg] rotate-0",
  },
  {
    name: "Vanilla Milkshake",
    color: "white",
    num:17,
    rotation: "md:rotate-[-8deg] rotate-0",
  },
  {
    name: "Franky Rizardo",
    color: "black",
    num:18,
    // rotation: "md:rotate-[8deg] rotate-0",
  },
];


export const events = [
  {
    id: 1,
    title: "MC4D Live",
    artist: "MC4D",
    date: "Fri, November 7",
    time: "8PM",
    venue: "Irving Plaza",
    price: 31,
    image: "/images/Events/image_6.png",
    category: "EDM",
    rating: 4.8,
    gradient: "from-slate-900/90 to-slate-800/90",
  },
  {
    id: 2,
    title: "Adventure Club",
    artist: "Adventure Club",
    date: "Fri, November 7",
    time: "9PM",
    venue: "Terminal 5",
    price: 61,
    image: "/images/Events/image_2.png",
    category: "Electronic",
    rating: 4.9,
    gradient: "from-blue-900/90 to-blue-800/90",
  },
  {
    id: 3,
    title: "Ely Oaks",
    artist: "Ely Oaks",
    date: "Fri, November 7",
    time: "10PM",
    venue: "Car Park",
    price: 21,
    image: "/images/Events/image_14.png",
    category: "House",
    rating: 4.7,
    gradient: "from-purple-900/90 to-purple-800/90",
  },
  {
    id: 4,  
    title: "Mathame",
    artist: "Mathame",
    date: "Fri, November 7",
    time: "10PM",
    venue: "63 Scott",
    price: 67,
    image: "/images/Events/image_4.png",
    category: "Techno",
    rating: 4.9,
    gradient: "from-indigo-900/90 to-indigo-800/90",
  },
  {
    id: 5,
    title: "Sunset Beats",
    artist: "DJ Sunset",
    date: "Sat, November 8",
    time: "9PM",
    venue: "Beach Club",
    price: 45,
    image: "/images/Events/image_5.png",
    category: "House",
    rating: 4.6,
    gradient: "from-orange-900/90 to-red-800/90",
  },
  {
    id: 6,
    title: "Neon Nights",
    artist: "Neon Collective",
    date: "Sat, November 8",
    time: "11PM",
    venue: "Club Mirage",
    price: 55,
    image: "/images/Events/image_7.png",
    category: "EDM",
    rating: 4.8,
    gradient: "from-pink-900/90 to-purple-800/90",
  },
  {
    id: 7,
    title: "Underground Vibes",
    artist: "Bass Collective",
    date: "Sun, November 9",
    time: "10PM",
    venue: "The Basement",
    price: 35,
    image: "/images/Events/image_8.png",
    category: "Dubstep",
    rating: 4.7,
    gradient: "from-teal-900/90 to-cyan-800/90",
  },
  {
    id: 8,
    title: "Electric Dreams",
    artist: "Dreamwave",
    date: "Sun, November 9",
    time: "8PM",
    venue: "Sky Lounge",
    price: 50,
    image: "/images/Events/image_9.png",
    category: "Trance",
    rating: 4.9,
    gradient: "from-violet-900/90 to-indigo-800/90",
  },
  {
    id: 9,
    title: "Rhythm Revolution",
    artist: "Beat Masters",
    date: "Mon, November 10",
    time: "9PM",
    venue: "Revolution Hall",
    price: 40,
    image: "/images/Events/image_10.png",
    category: "Electronic",
    rating: 4.5,
    gradient: "from-emerald-900/90 to-green-800/90",
  },
  {
    id: 10,
    title: "Cosmic Waves",
    artist: "Space DJ",
    date: "Mon, November 10",
    time: "11PM",
    venue: "Cosmos Club",
    price: 60,
    image: "/images/Events/image_11.png",
    category: "Psytrance",
    rating: 4.8,
    gradient: "from-fuchsia-900/90 to-pink-800/90",
  },
  {
    id: 11,
    title: "Bass Drop",
    artist: "Heavy Bass",
    date: "Tue, November 11",
    time: "10PM",
    venue: "Bass Station",
    price: 38,
    image: "/images/Events/image_12.png",
    category: "Drum & Bass",
    rating: 4.6,
    gradient: "from-red-900/90 to-orange-800/90",
  },
  {
    id: 12,
    title: "Midnight Groove",
    artist: "Groove Squad",
    date: "Tue, November 11",
    time: "12AM",
    venue: "Late Night Lounge",
    price: 42,
    image: "/images/Events/image_13.png",
    category: "Deep House",
    rating: 4.7,
    gradient: "from-amber-900/90 to-yellow-800/90",
  },
];

export const cities = ["New York", "Miami", "Chicago", "LA"];
export const filters = [
  { icon: "📅", label: "Date" },
  { icon: "📍", label: "Venue" },
  { icon: "🔥", label: "Popular" },
  { icon: "🎯", label: "Sort By" },
];


 export const artists = [
  {
    id: 1,
    name: "Akash Kapoor",
    image: "/images/Events/image_1.png",
    gradient: "from-sky-200 to-blue-300",
  },
  {
    id: 2,
    name: "Shubhika Marar",
    image: "/images/Events/image_2.png",
    gradient: "from-purple-300 to-indigo-400",
  },
  {
    id: 3,
    name: "DJ Ali Burrni",
    image: "/images/Events/image_3.png",
    gradient: "from-gray-200 to-gray-400",
  },
  {
    id: 4,
    name: "Ashna Malik",
    image: "/images/Events/image_4.png",
    gradient: "from-amber-100 to-yellow-200",
  },
  {
    id: 5,
    name: "Hamza Rahimtula",
    image: "/images/Events/image_5.png",
    gradient: "from-blue-200 to-cyan-300",
  },
  {
    id: 6,
    name: "Nash",
    image: "/images/Events/image_7.png",
    gradient: "from-red-300 to-orange-400",
  },
  {
    id: 7,
    name: "Tyler",
    image: "/images/Events/image_8.png",
    gradient: "from-gray-300 to-slate-400",
  },
  {
    id: 8,
    name: "Sarah Chen",
    image: "/images/Events/image_9.png",
    gradient: "from-pink-200 to-rose-300",
  },
];